spring.liquibase.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.datasource.url=jdbc:postgresql://localhost:52001/
spring.datasource.name=shop
spring.datasource.username=shop
spring.datasource.password=shop1

spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
spring.application.name=application
